[package]
name = "ua2_contracts"
version = "0.1.0"
edition = "2023_11"
description = "UA2 smart contract suite"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v2.0.0" }
starknet = "2.11.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.50.0" }

[[target.starknet-contract]]
casm = true
sierra = true
