name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci

  lint_type_test:
    name: Lint, typecheck, build and test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run ci

  cairo:
    name: Cairo build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
      - name: Install Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
      - run: npm run contracts:build
      - run: npm run contracts:test
      - name: Scripts sanity (no execution)
        run: |
          bash -n packages/contracts/scripts/helpers.sh
          bash -n packages/contracts/scripts/declare_ua2.sh
          bash -n packages/contracts/scripts/deploy_ua2.sh
          bash -n packages/contracts/scripts/upgrade_ua2.sh
